### ISSUE TITLE
'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by Kryp7os** [Tw1sm/PySQLRecon#11]
![image](https://github.com/Tw1sm/PySQLRecon/assets/98974230/d47f013c-6ce9-4d38-a378-514b170e4df1)
Keep running into this error. Tried different commands and resulted in the same error. Installed using pip3. Any fixes?

**Comment by Tw1sm** [comment]
Thanks for the bug report. I probably need to wrap [these](https://github.com/Tw1sm/PySQLRecon/blob/ce01e04ea4a34581d68b51f546ebb8b04082ee61/pysqlrecon/modules/info.py#L79) `decode()` calls in a try/except

**Comment by Kryp7os** [comment]
It looks like in the latest version of python3, the decode function was removed and decodes to utf-8 by default. Found this recommendation saying to remove decode() altogether. https://stackoverflow.com/questions/28583565/str-object-has-no-attribute-decode-python-3-error

**Comment by Tw1sm** [comment]
What version of python do you have installed? My test box still has `3.11.8` and it looks like the `decode()` call is necessary for that version 
![image](https://github.com/Tw1sm/PySQLRecon/assets/37981031/4daef8ce-b908-435a-bef2-db494357d943)

**Comment by Kryp7os** [comment]
![image](https://github.com/Tw1sm/PySQLRecon/assets/98974230/3060b159-52e2-4b79-a5b7-f45068b02645)

Ah, I'm running 3.11.6. I'll update python and try to run the command again.

**Comment by Tw1sm** [comment]
It's also possible that your system is using a different version of Python outside of that poetry virtual environment (your first screenshot looked like `pysqlrecon` was being run outside of any venv). I'd be interested in knowing what version is running there, in case it's Python 3.12+

**Comment by Kryp7os** [comment]
![Screenshot 2024-05-07 153808](https://github.com/Tw1sm/PySQLRecon/assets/98974230/2f738891-43b0-4fa7-a7c2-0e44822ca184)
![image](https://github.com/Tw1sm/PySQLRecon/assets/98974230/8070565a-2195-4d28-b3d2-95248b424ea1)

Tried both methods, updating python did go to 3.12. Still no luck

**Comment by Tw1sm** [comment]
Odd - I just pushed a potential fix (just wrapping all those decodes in the info module in a try/except) in the `fix/decoding` branch. Can you give that branch a try and let me know if it works?

**Comment by Kryp7os** [comment]
Sure

**Comment by Kryp7os** [comment]
Nothing. Seems like any command is triggering the error
![image](https://github.com/Tw1sm/PySQLRecon/assets/98974230/b6b343c4-0b4f-4e72-9e0b-75ff3e0902bb)

**Comment by Tw1sm** [comment]
Likely happening in this function then [https://github.com/Tw1sm/PySQLRecon/blob/main/pysqlrecon/lib/__init__.py#L209](https://github.com/Tw1sm/PySQLRecon/blob/main/pysqlrecon/lib/__init__.py#L209) which is pulled from Impacket. 

Are you able to use Impacket's `mssqlclient.py` example script with your test SQL server? 

Another thing, though it seems unlikely to cause the error but. is the `will` user you're authenticating with a domain user or a SQL account? If it is a domain user, try specifying the domain with `-d` or if a SQL account, try `--sql-auth`

**Comment by Kryp7os** [comment]
Yup, that did the trick, it was user error. Only needed to specify the --sql-auth. I appreciate your help!
