### ISSUE TITLE
Kerberos authentication does not work

### ISSUE THREAD

**Issue by enj5oy** [Tw1sm/PySQLRecon#15]
![pysqlrecon](https://github.com/user-attachments/assets/e5c42a7d-cdcd-4d44-8df3-b45e8eaff820)

**Comment by Tw1sm** [comment]
Based on the screenshot, you need to specify the IP address of the KDC with `--dc-ip` for it to work. A modification could probably be made to the code so it attempts to hit the domain specified with `-d` on 88 by default.

**Comment by enj5oy** [comment]
Yes, you're right, it works with the --dc-ip flag.
