### ISSUE TITLE
db_owner is not working

### ISSUE THREAD

**Issue by starley00** [Tw1sm/PySQLRecon#3]
Module doesn't show db_owner
![1](https://github.com/Tw1sm/PySQLRecon/assets/100708808/f59b48c7-2871-4fed-afea-814890606573)
![2](https://github.com/Tw1sm/PySQLRecon/assets/100708808/b026c5e5-984f-4065-bd46-cc782b252500)
![3](https://github.com/Tw1sm/PySQLRecon/assets/100708808/029bcceb-bac3-4832-8b08-7188d43fad78)
![4](https://github.com/Tw1sm/PySQLRecon/assets/100708808/56143ce6-a301-44ef-bd1d-3d970ac29f82)

**Comment by Tw1sm** [comment]
Thanks for the bug report! Should be fixed now, please reopen if the issue persists
