### ISSUE TITLE
Invalid column name 'sysadmin'

### ISSUE THREAD

**Issue by starley00** [Tw1sm/PySQLRecon#6]
Invalid column name 'sysadmin'
![1](https://github.com/Tw1sm/PySQLRecon/assets/100708808/14c8015a-c8c3-47eb-87b5-4af7bf68a123)
![2](https://github.com/Tw1sm/PySQLRecon/assets/100708808/ef8df775-c29b-4540-8a38-601663da10bd)

**Comment by Tw1sm** [comment]
That is expected behavior - you need to use double quotes around your query if you are using single quotes inside it `"select is_srvrolemember('sysadmin')"`

```
poetry run pysqlrecon --quiet --dc-ip 192.168.0.235 -d redania.local -u user -p Password1 -t 192.168.0.235 query --query "select is_srvrolemember('sysadmin')"
[13:08:27] INFO     Connecting to 192.168.0.235:1433
[13:08:27] INFO     Executing custom query on 192.168.0.235

┏━━━┓
┃   ┃
┡━━━┩
│ 0 │
└───┘
```
