### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [Tw1sm/PySQLRecon#8]
It would be very helpful if you could tag releases as well. This would make tracking, especially for distributions, easier.

Thanks

**Comment by Tw1sm** [comment]
Tagged the current release, will tag new releases in the future too 👍

**Comment by fabaff** [comment]
`pysqlrecon` is on the way [into Nixpkgs](https://github.com/NixOS/nixpkgs/pull/284592).

**Comment by Tw1sm** [comment]
This is awesome, thanks for sharing!
